

# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# [START cloudbuild_run_example_builddeploy]
steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/${{ secrets.GCP_PROJECT }}/gcollector', '.']
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/${{ secrets.GCP_PROJECT }}/gcollector']
  # Deploy container image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'gcollector', '--image', 'gcr.io/${{ secrets.GCP_PROJECT }}/gcollector', '--region', 'us-east1-b', '--platform', 'managed', '--allow-unauthenticated']
images:
  - gcr.io/${{ secrets.GCP_PROJECT }}/gcollector
# [END cloudbuild_run_example_builddeploy]