spring:
  main:
    allow-circular-references: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher



  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${System.getenv("ENDPOINT")}:3306/${System.getenv("SCHEMA")}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${System.getenv("USER")}
    password: ${System.getenv("PW")}

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      default_batch_fetch_size: 1000
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    database: mysql




