spring:
  main:
    allow-circular-references: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher



  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${ENDPOINT}:3306/${SCHEMA}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${USER}
    password: ${PW}


  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      default_batch_fetch_size: 1000
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    database: mysql

  security:
    oauth2:
      client:
        registration:
          google:

            client-id: ${CLIENTID}
            client-secret: ${CLIENTSECRET}
            scope: https://www.googleapis.com/auth/userinfo.profile

server:
  port: 8071




